export {default as Footer} from './Footer'
export {default as Hero} from './Hero'
export {default as Jokes} from './FeaturedApps/Jokes'
export {default as Modal} from './Modal'
export {default as Navbar} from './Navbar'
export {default as ProjectDetail} from './ProjectDetail'
export {default as Projects} from './Projects'